config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :configs
  resources :projets
  resources :connaissances
  resources :langues
  resources :formations
  resources :competences
  resources :articles
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projet.rb
class Projet < ApplicationRecord
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  before_action :authenticate_user!, :set_projet, only: [:show, :edit, :update, :destroy]

  # GET /projets
  # GET /projets.json
  def index
    @projets = Projet.all
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
  end

  # GET /projets/new
  def new
    @projet = Projet.new
  end

  # GET /projets/1/edit
  def edit
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(projet_params)

    respond_to do |format|
      if @projet.save
        format.html { redirect_to @projet, notice: 'Projet was successfully created.' }
        format.json { render :show, status: :created, location: @projet }
      else
        format.html { render :new }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projets/1
  # PATCH/PUT /projets/1.json
  def update
    respond_to do |format|
      if @projet.update(projet_params)
        format.html { redirect_to @projet, notice: 'Projet was successfully updated.' }
        format.json { render :show, status: :ok, location: @projet }
      else
        format.html { render :edit }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet.destroy
    respond_to do |format|
      format.html { redirect_to projets_url, notice: 'Projet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet
      @projet = Projet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projet_params
      params.require(:projet).permit(:description)
    end
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/projets/_form.html.erb
<%= form_with(model: projet) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button 'Enregistrer', class: "btn btn-default" %>

    <% if form.object.persisted? %>
      <%= link_to 'Supprimer', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Voulez-vous vraiement supprimer cette item?" } %>
    <% end %>
  </div>
<% end %>

app/views/projets/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Modifier projet</h1>

    <%= render 'form', projet: @projet %>
  </div>
</div>

app/views/projets/index.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="h2">Projets</h1>

    <% if @projets.exists? %>
      <%= link_to 'Ajouter projet', new_projet_path, class: "btn btn-default" %>
    <% end %>
  </div>

  <% if @projets.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Description</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @projets.each do |projet| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= projet.description %></td>
            
            <td>
              <%= link_to "Voir", projet, class: "btn btn-default" %>
              <%= link_to "Modifier", edit_projet_path(projet), class: "btn btn-default" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center">
        <p class="text-xl font-semibold mb-4">Ajouter un nouveau projet</p>
      <%= link_to 'Ajouter projet', new_projet_path, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/projets/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Ajouter projet</h1>

    <%= render 'form', projet: @projet %>

    <%= link_to 'Retour', projets_path, class: "link" %>
  </div>
</div>

app/views/projets/show.html.erb
<div class="container mx-auto my-8 px-4">
    <p class="text-lg font-semibold">Description:</p>
  <p class="leading-normal"><%= @projet.description %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Modifier', edit_projet_path(@projet), class: "btn btn-default mr-4" %>
    <%= link_to 'Retour', projets_path, class: "btn btn-default" %>
  </div>
</div>