config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :configs
  resources :projets
  resources :connaissances
  resources :langues
  resources :formations
  resources :competences
  resources :articles
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :authenticate_user!, :set_formation, only: [:show, :edit, :update, :destroy]

  # GET /formations
  # GET /formations.json
  def index
    @formations = Formation.all
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
  end

  # POST /formations
  # POST /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to @formation, notice: 'Formation was successfully created.' }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation was successfully updated.' }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url, notice: 'Formation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params.require(:formation).permit(:formation)
    end
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/views/formations/_form.html.erb
<%= form_with(model: formation) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">
    <%= form.label :formation, class: "label" %>
    <%= form.text_field :formation, class: "input" %>
  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button 'Enregistrer', class: "btn btn-default" %>

    <% if form.object.persisted? %>
      <%= link_to 'Supprimer', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Voulez-vous vraiement supprimer cette item?" } %>
    <% end %>
  </div>
<% end %>

app/views/formations/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Modifier formation</h1>

    <%= render 'form', formation: @formation %>
  </div>
</div>

app/views/formations/index.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="h2">Formations</h1>

    <% if @formations.exists? %>
      <%= link_to 'Ajouter formation', new_formation_path, class: "btn btn-default" %>
    <% end %>
  </div>

  <% if @formations.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Formation</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @formations.each do |formation| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= formation.formation %></td>
            
            <td>
              <%= link_to "Voir", formation, class: "btn btn-default" %>
              <%= link_to "Modifier", edit_formation_path(formation), class: "btn btn-default" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center">
        <p class="text-xl font-semibold mb-4">Ajouter une nouvelle formation</p>
      <%= link_to 'Ajouter formation', new_formation_path, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/formations/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Ajouter formation</h1>

    <%= render 'form', formation: @formation %>

    <%= link_to 'Retour', formations_path, class: "link" %>
  </div>
</div>

app/views/formations/show.html.erb
<div class="container mx-auto my-8 px-4">
    <p class="text-lg font-semibold">Formation:</p>
  <p class="leading-normal"><%= @formation.formation %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Modifier', edit_formation_path(@formation), class: "btn btn-default mr-4" %>
    <%= link_to 'Retour', formations_path, class: "btn btn-default" %>
  </div>
</div>