config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :configs
  resources :projets
  resources :connaissances
  resources :langues
  resources :formations
  resources :competences
  resources :articles
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/langue.rb
class Langue < ApplicationRecord
end

app/controllers/langues_controller.rb
class LanguesController < ApplicationController
  before_action :authenticate_user!, :set_langue, only: [:show, :edit, :update, :destroy]

  # GET /langues
  # GET /langues.json
  def index
    @langues = Langue.all
  end

  # GET /langues/1
  # GET /langues/1.json
  def show
  end

  # GET /langues/new
  def new
    @langue = Langue.new
  end

  # GET /langues/1/edit
  def edit
  end

  # POST /langues
  # POST /langues.json
  def create
    @langue = Langue.new(langue_params)

    respond_to do |format|
      if @langue.save
        format.html { redirect_to @langue, notice: 'Langue was successfully created.' }
        format.json { render :show, status: :created, location: @langue }
      else
        format.html { render :new }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langues/1
  # PATCH/PUT /langues/1.json
  def update
    respond_to do |format|
      if @langue.update(langue_params)
        format.html { redirect_to @langue, notice: 'Langue was successfully updated.' }
        format.json { render :show, status: :ok, location: @langue }
      else
        format.html { render :edit }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langues/1
  # DELETE /langues/1.json
  def destroy
    @langue.destroy
    respond_to do |format|
      format.html { redirect_to langues_url, notice: 'Langue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_langue
      @langue = Langue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def langue_params
      params.require(:langue).permit(:nom, :description, :note)
    end
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/views/langues/_form.html.erb
<%= form_with(model: langue) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">
    <%= form.label :nom, class: "label" %>
    <%= form.text_field :nom, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :note, class: "label" %>
    <%= form.number_field :note, class: "input" %>
  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button 'Enregistrer', class: "btn btn-default" %>

    <% if form.object.persisted? %>
      <%= link_to 'Supprimer', form.object, class: "btn btn-default", method: :delete, data: { remote: true, confirm: "Voulez-vous  vraiement supprimer cette item?" } %>
    <% end %>
  </div>
<% end %>

app/views/langues/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Modifier langue</h1>

    <%= render 'form', langue: @langue %>
  </div>
</div>

app/views/langues/index.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="h2">Langues</h1>

    <% if @langues.exists? %>
      <%= link_to 'Ajouter langue', new_langue_path, class: "btn btn-default" %>
    <% end %>
  </div>

  <% if @langues.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Nom</th>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Description</th>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Note</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @langues.each do |langue| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= langue.nom %></td>
                          <td class="p-3"><%= langue.description %></td>
                          <td class="p-3"><%= langue.note %></td>
            
            <td>
              <%= link_to "Voir", langue, class: "btn btn-default" %>
              <%= link_to "Modifier", edit_langue_path(langue), class: "btn btn-default" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center">
        <p class="text-xl font-semibold mb-4">Ajouter une nouvelle langue</p>
      <%= link_to 'Ajouter langue', new_langue_path, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/langues/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Ajouter langue</h1>

    <%= render 'form', langue: @langue %>

    <%= link_to 'Retour', langues_path, class: "link" %>
  </div>
</div>

app/views/langues/show.html.erb
<div class="container mx-auto my-8 px-4">
    <p class="text-lg font-semibold">Nom:</p>
  <p class="leading-normal"><%= @langue.nom %></p>

    <p class="text-lg font-semibold">Description:</p>
  <p class="leading-normal"><%= @langue.description %></p>

    <p class="text-lg font-semibold">Note:</p>
  <p class="leading-normal"><%= @langue.note %></p>

    <div class="flex items-center justify-start mt-6">
    <%= link_to 'Modifier', edit_langue_path(@langue), class: "btn btn-default mr-4" %>
    <%= link_to 'Retour', langues_path, class: "btn btn-default" %>
  </div>
</div>