config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :configs
  resources :projets
  resources :connaissances
  resources :langues
  resources :formations
  resources :competences
  resources :articles
  resources :posts
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :body
end

app/models/competence.rb
class Competence < ApplicationRecord
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/connaissance.rb
class Connaissance < ApplicationRecord
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/models/langue.rb
class Langue < ApplicationRecord
end

app/models/projet.rb
class Projet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :authenticate_user!, :set_config, only: [:show, :edit, :update, :destroy]

  # GET /configs
  # GET /configs.json
  def index
    @configs = Config.all
  end

  # GET /configs/1
  # GET /configs/1.json
  def show
  end

  # GET /configs/new
  def new
    @config = Config.new
  end

  # GET /configs/1/edit
  def edit
  end

  # POST /configs
  # POST /configs.json
  def create
    @config = Config.new(config_params)

    respond_to do |format|
      if @config.save
        format.html { redirect_to @config, notice: 'Config was successfully created.' }
        format.json { render :show, status: :created, location: @config }
      else
        format.html { render :new }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configs/1
  # PATCH/PUT /configs/1.json
  def update
    respond_to do |format|
      if @config.update(config_params)
        format.html { redirect_to @config, notice: 'Config was successfully updated.' }
        format.json { render :show, status: :ok, location: @config }
      else
        format.html { render :edit }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configs/1
  # DELETE /configs/1.json
  def destroy
    @config.destroy
    respond_to do |format|
      format.html { redirect_to configs_url, notice: 'Config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = Config.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.require(:config).permit(:nom, :post, :adresse)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @competences = Competence.order('id ASC')
    @config = Config.first()
    @connaissances = Connaissance.order('id ASC')
    @formations = Formation.order('id ASC')
    @langues = Langue.order('id ASC')
    @projets = Projet.order('id ASC')
    @articles = Article.where('id != ?','3').order('id ASC')
    @rails = Article.where('id = ?','3').first

  end
end

app/controllers/langues_controller.rb
class LanguesController < ApplicationController
  before_action :authenticate_user!, :set_langue, only: [:show, :edit, :update, :destroy]

  # GET /langues
  # GET /langues.json
  def index
    @langues = Langue.all
  end

  # GET /langues/1
  # GET /langues/1.json
  def show
  end

  # GET /langues/new
  def new
    @langue = Langue.new
  end

  # GET /langues/1/edit
  def edit
  end

  # POST /langues
  # POST /langues.json
  def create
    @langue = Langue.new(langue_params)

    respond_to do |format|
      if @langue.save
        format.html { redirect_to @langue, notice: 'Langue was successfully created.' }
        format.json { render :show, status: :created, location: @langue }
      else
        format.html { render :new }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langues/1
  # PATCH/PUT /langues/1.json
  def update
    respond_to do |format|
      if @langue.update(langue_params)
        format.html { redirect_to @langue, notice: 'Langue was successfully updated.' }
        format.json { render :show, status: :ok, location: @langue }
      else
        format.html { render :edit }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langues/1
  # DELETE /langues/1.json
  def destroy
    @langue.destroy
    respond_to do |format|
      format.html { redirect_to langues_url, notice: 'Langue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_langue
      @langue = Langue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def langue_params
      params.require(:langue).permit(:nom, :description, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/competences_helper.rb
module CompetencesHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/connaissances_helper.rb
module ConnaissancesHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patrick Simard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-white">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="mb-4">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to "Patrick Simard", root_path, class:"link text-xl tracking-tight font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">

            <% if user_signed_in? %>
              <nav class="relative select-none bg-grey lg:flex lg:items-stretch w-full">
                <div class="lg:flex lg:items-stretch lg:flex-no-shrink lg:flex-grow">
                  <div class="lg:flex lg:items-stretch lg:justify-end ml-auto">
                    <%= link_to "Articles", articles_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Compétences", competences_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Configs", configs_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Conaissances", connaissances_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Formations", formations_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Langue", langues_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Projets", projets_path, class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                    <%= link_to "Déconnexion", destroy_user_session_path, :method=>'delete', class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-black no-underline flex items-center hover:bg-grey-dark"%>
                  </div>
                </div>
              </nav>
            <% else %>
                <%= link_to "Ce connecter", new_user_session_path , class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <% end %>

          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>

    <div class="bg-gray-300 ">
      <div class="flex pb-5 px-3 m-auto pt-5 border-t text-gray-800 text-sm flex-col
          md:flex-row max-w-6xl">
          <div class="mt-2">CV - Patrick Simard 2020</div>
          <div class="md:flex-auto md:flex-row-reverse mt-2 flex-row flex">
            <a target="_blanc" href="https://www.facebook.com/elpat" class="w-6 mx-1">
                <svg class="fill-current cursor-pointer text-gray-500 hover:text-gray-400" width="100%" height="100%" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule: evenodd; clip-rule: evenodd; stroke-linejoin: round; stroke-miterlimit: 2;">
                  <path id="Facebook" d="M24,12c0,6.627 -5.373,12 -12,12c-6.627,0 -12,-5.373 -12,-12c0,-6.627
                      5.373,-12 12,-12c6.627,0 12,5.373
                      12,12Zm-11.278,0l1.294,0l0.172,-1.617l-1.466,0l0.002,-0.808c0,-0.422
                      0.04,-0.648 0.646,-0.648l0.809,0l0,-1.616l-1.295,0c-1.555,0 -2.103,0.784
                      -2.103,2.102l0,0.97l-0.969,0l0,1.617l0.969,0l0,4.689l1.941,0l0,-4.689Z"></path>
                </svg>
            </a>
            <a target="_blanc" href="https://www.linkedin.com/in/webiummedia/" class="w-6 mx-1">
                <svg class="fill-current cursor-pointer text-gray-500 hover:text-gray-400" width="100%" height="100%" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule: evenodd; clip-rule: evenodd; stroke-linejoin: round; stroke-miterlimit: 2;">
                  <path id="Shape" d="M7.3,0.9c1.5,-0.6 3.1,-0.9 4.7,-0.9c1.6,0 3.2,0.3 4.7,0.9c1.5,0.6 2.8,1.5
                      3.8,2.6c1,1.1 1.9,2.3 2.6,3.8c0.7,1.5 0.9,3 0.9,4.7c0,1.7 -0.3,3.2
                      -0.9,4.7c-0.6,1.5 -1.5,2.8 -2.6,3.8c-1.1,1 -2.3,1.9 -3.8,2.6c-1.5,0.7
                      -3.1,0.9 -4.7,0.9c-1.6,0 -3.2,-0.3 -4.7,-0.9c-1.5,-0.6 -2.8,-1.5
                      -3.8,-2.6c-1,-1.1 -1.9,-2.3 -2.6,-3.8c-0.7,-1.5 -0.9,-3.1 -0.9,-4.7c0,-1.6
                      0.3,-3.2 0.9,-4.7c0.6,-1.5 1.5,-2.8 2.6,-3.8c1.1,-1 2.3,-1.9
                      3.8,-2.6Zm-0.3,7.1c0.6,0 1.1,-0.2 1.5,-0.5c0.4,-0.3 0.5,-0.8 0.5,-1.3c0,-0.5
                      -0.2,-0.9 -0.6,-1.2c-0.4,-0.3 -0.8,-0.5 -1.4,-0.5c-0.6,0 -1.1,0.2
                      -1.4,0.5c-0.3,0.3 -0.6,0.7 -0.6,1.2c0,0.5 0.2,0.9 0.5,1.3c0.3,0.4 0.9,0.5
                      1.5,0.5Zm1.5,10l0,-8.5l-3,0l0,8.5l3,0Zm11,0l0,-4.5c0,-1.4 -0.3,-2.5
                      -0.9,-3.3c-0.6,-0.8 -1.5,-1.2 -2.6,-1.2c-0.6,0 -1.1,0.2 -1.5,0.5c-0.4,0.3
                      -0.8,0.8 -0.9,1.3l-0.1,-1.3l-3,0l0.1,2l0,6.5l3,0l0,-4.5c0,-0.6 0.1,-1.1
                      0.4,-1.5c0.3,-0.4 0.6,-0.5 1.1,-0.5c0.5,0 0.9,0.2 1.1,0.5c0.2,0.3 0.4,0.8
                      0.4,1.5l0,4.5l2.9,0Z"></path>
                </svg>
            </a>
          </div>
      </div>
    </div>

  </body>
</html>